### PR TITLE
feat: use downlevel-dts to generate TS 3.4 compatible types

### PR DESCRIPTION
**Pull request by trivikr**
*Issue #, if available:*
Fixes: https://github.com/aws/aws-sdk-js-v3/issues/1919

*Description of changes:*
use downlevel-dts to generate TS 3.4 compatible types for clients in AWS SDK for JavaScript

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by trivikr** [comment]
aws-sdk-js-v3 https://github.com/aws/aws-sdk-js-v3/pull/1943

**Review by AllanZhengYP — APPROVED** [review]

**Review by AllanZhengYP — CHANGES_REQUESTED** [review]
Should this be in the AWS repo only? I feel like other SDK implementer should not use this.

**Comment by trivikr** [comment]
> Should this be in the AWS repo only? I feel like other SDK implementer should not use this.

If we put this code in smithy-typescript, it would a recommendation from AWS to support old versions of TypeScript type definitions. And I would like to have that explicit recommendation.

Without this recommendation, the SDK implementers will not be aware that their TypeScript types may not work with old versions of TypeScript. The implementer is always free to remove postbuild script, downlevel-dts dependency and typesVersions key.

**Comment by AllanZhengYP** [comment]
OK I was assuming the downleveled `*.d.ts` will be shipped to all users, that will compromise the user experience, until to understand [`typesVersion`](https://github.com/awslabs/smithy-typescript/pull/266/files#diff-0c0e1e84e2af3ae67e178028a9d279aabe6f2cc962bffd21a0fafadb27e4d88fR42-R45). According to the [TypeScript doc](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-1.html#version-selection-with-typesversions). The consumers will only use the downleveled `*.d.ts` when their local TypeScript version is older. The consumers using newer TypeScript can still use the newer features. It's just the built client will generate and be shipped with multiple versions of `*.d.ts`. 

It has some overhead regarding the download package size. But they don't goes to the `.js` file and it helpers users able to support broader development environments, outweights the drawbacks.

**Review by AllanZhengYP — APPROVED** [review]
Approve again

**Pull request merged**
