### PR TITLE
Bump typescript to 4.7.3

### PR DESCRIPTION
**Pull request by trivikr**
*Issue #, if available:*
Internal JS-3363

*Description of changes:*
Bump typescript to 4.7.3

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by trivikr** [comment]
Internal JS-3393 discusses blockers with updating typedoc to `v0.22.x`

**Comment by eduardomourar** [comment]
We have been able to successfully migrate to typedoc `v0.23.x` (output example [here](https://stedi.github.io/stedi-sdk-javascript/clients/guides/docs/index.html)). @trivikr, are you interested in us pushing upstream the changes to the whole documentation generation?

**Comment by trivikr** [comment]
> are you interested in us pushing upstream the changes to the whole documentation generation?

Yeah! That would be very helpful.

I've created a feature request at https://github.com/aws/aws-sdk-js-v3/issues/4134
Can you post your findings there?

**Review by AndrewFossAWS — APPROVED** [review]

**Review by kuhe — APPROVED** [review]

**Comment by trivikr** [comment]
Closing as we're still blocked on bumping typedoc in https://github.com/aws/aws-sdk-js-v3/issues/4134

Bumping TypeScript will be revisited when we either bump typedoc, or switch to a different solution for documentation.

**Comment by trivikr** [comment]
If you're generating client using smithy-typescript, and not using typedoc or using a supported version of typedoc, you can always bump typescript version in the generated package.json

**Pull request closed without merging**
